[project]
name = "fastapi-blog-api"
version = "0.1.0"
description = "A professional Blog API built with FastAPI, SQLAlchemy, and JWT Authentication"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "passlib[argon2]",
    "python-jose[cryptography]",
    "python-multipart"
]
